ETicketing/Controllers/ActorController.cs
using CoreModule.Source.Dto.Actor;
using CoreModule.Source.Entity;
using CoreModule.Source.Exceptions;
using CoreModule.Source.Service;
using CoreModule.Source.Service.Image;
using CoreModule.UOW;
using ETicketing.Extensions;
using ETicketing.ViewModels.Actor;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using NToastNotify;

namespace ETicketing.Controllers
{
 [Authorize(Roles =ApplicationUser.RoleAdmin)]
    public class ActorController : Controller
    {
        private readonly UnitOfWorkInterface _unitOfWork;
        private readonly ILogger<ActorController> _logger;
        private readonly IToastNotification _notify;
        private readonly ActorServiceInterface _actorService;
        private readonly ImageUploaderInterface _imageUploader;
        public ActorController(UnitOfWorkInterface unitOfWork,
            ILogger<ActorController> logger,
            IToastNotification notify,
            ActorServiceInterface actorService,
            ImageUploaderInterface imageUploader)
        {
            _unitOfWork = unitOfWork;
            _logger = logger;
            _notify = notify;
            _actorService = actorService;
            _imageUploader = imageUploader;
        }
        public async Task<IActionResult> Index()
        {
          var user=  await this.GetCurrentUser();
            var actors = await _unitOfWork.Actors.GetAllAsync();
            var actorIndexViewModel = actors.Select(a => new ActorIndexViewModel
            {
                Id = a.Id,
                Name = a.FullName,
                Description = a.Description,
                Image = a.Image ?? ""
            });
            return View(actorIndexViewModel);
        }
        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(ActorCreateViewModel model)
        {
            try
            {
                if(ModelState.IsValid)
                {
                    string? imagePath = await ValidateAndUploadImage(model.Image);
                    var createDto = new ActorCreateDto(model.Name, model.Description, imagePath);
                    await _actorService.Create(createDto);
                    _notify.AddSuccessToastMessage("Actor Added Successfully");
                    return RedirectToAction(nameof(Index));
                }
            }
            catch (Exception ex)
            {

                _logger.LogError(ex.Message);
                _notify.AddErrorToastMessage(ex.Message);
            }
            return View(model);
        }

        [HttpGet]
        public async Task<IActionResult> Update(int id)
        {
            try
            {
                var actor = await _unitOfWork.Actors.GetByIdAsync(id) ?? throw new ActorNotFoundException();
                var updateViewModel = new ActorUpdateViewModel
                {
                    Id = actor.Id,
                    Name = actor.FullName,
                    Description = actor.Description,
                    ImageSource = actor.Image
                };
                return View(updateViewModel);
            }
            catch (Exception ex)
            {
                _logger.LogError(ex.Message);
                _notify.AddErrorToastMessage(ex.Message);
            }
            return RedirectToAction(nameof(Index));
        }

        [HttpPost]
        public async Task<IActionResult> Update(ActorUpdateViewModel model)
        {
            try
            {
                if(ModelState.IsValid)
                {
                    string? imagePath = await ValidateAndUploadImage(model.Image);
                    var updateDto = new ActorUpdateDto(model.Id, model.Name, model.Description, imagePath);
                    await _actorService.Update(updateDto);
                    return RedirectToAction(nameof(Index));
                }
            }
            catch (Exception ex)
            {

                _logger.LogError(ex.Message);
                _notify.AddErrorToastMessage(ex.Message);
            }
            return View(model);
        }
        public async Task<IActionResult> Details(int id)
        {
            try
            {
                var actor = await _unitOfWork.Actors.GetByIdAsync(id) ?? throw new ActorNotFoundException();
                ActorDetailsViewModel actorDetailsViewModel = ConfigureActorDetails(actor);
                return View(actorDetailsViewModel);
            }
            catch (Exception ex)
            {
                _logger.LogError(ex.Message);
                _notify.AddErrorToastMessage(ex.Message);
            }
            return RedirectToAction(nameof(Index));
        }

      [HttpGet]
        public async Task<IActionResult> Delete(int id)
        {
           
            await _actorService.Remove(id);
            return RedirectToAction(nameof(Index));
        }

        private async Task<string> ValidateAndUploadImage(IFormFile file)
        {
            string? imagePath = null;
            if (file != null &&file.Length > 0)
            {
                imagePath = await _imageUploader.UploadToTemporary(file);
            }

            return imagePath;
        }
        private static ActorDetailsViewModel ConfigureActorDetails(CoreModule.Source.Entity.Actor actor)
        {
            return new ActorDetailsViewModel
            {
                id = actor.Id,
                Name = actor.FullName,
                Description = actor.Description,
                Image = actor.Image ?? ""
            };
        }
    }
}

ETicketing/Controllers/MovieController.cs
using CoreModule.Source.Dto.Movie;
using CoreModule.Source.Entity;
using CoreModule.Source.Exceptions;
using CoreModule.Source.Service;
using CoreModule.Source.Service.Image;
using CoreModule.UOW;
using ETicketing.ViewModels;
using ETicketing.ViewModels.Movie;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using NToastNotify;


namespace ETicketing.Controllers
{
    [Authorize(Roles = ApplicationUser.RoleAdmin)]
    public class MovieController : Controller
    {

        private readonly UnitOfWorkInterface _unitOfWork;
        private readonly ILogger<MovieController> _logger;
        private readonly IToastNotification _notify;
        private readonly MovieServiceInterface _movieService;
        private readonly ImageUploaderInterface _imageUploader;

        public MovieController(UnitOfWorkInterface unitOfWork,
            ILogger<MovieController> logger,
            IToastNotification notify,
            MovieServiceInterface movieService,
            ImageUploaderInterface imageUploader)
        {
            _unitOfWork = unitOfWork;
            _logger = logger;
            _notify = notify;
            _movieService = movieService;
            _imageUploader = imageUploader;
        }
        public async Task<IActionResult> Index(MovieIndexViewModel model)
        {
            var dropdowns = await GetDropdowns();
            SetDropdowns(dropdowns);
            var movieQueryable = _unitOfWork.Movies.GetQueryable();
            movieQueryable = FilterMovies(model, movieQueryable);
            var movies =  movieQueryable;
            var moviesDataModel = await movies.Select(a => new MovieViewModel
            {
                Id = a.Id,
                CinemaHall = a.CinemaHall.Name,
                Name = a.Name,
                StartDate  =a.StartDate.ToString("yyy-MM-dd hh:mm tt"),
                EndDate  =a.EndDate.ToString("yyy-MM-dd hh:mm tt"),
                Image = a.Image,
                TicketPrice = a.TicketPrice,
                Status = a.EndDate < DateTime.Now ? Movie.Expired:Movie.Available,
                MovieCategory = a.Category.Name
            }).ToListAsync();
            model.MovieDatas = moviesDataModel;
            return View(model);
        }
        public async Task<IActionResult> Create()
        {
            var dropdowns = await GetDropdowns();
            SetDropdowns(dropdowns);

            return View();
        }

     

        [HttpPost]
        public async Task<IActionResult> Create(MovieCreatViewModel model)
        {
                var dropdowns = await GetDropdowns();
                SetDropdowns(dropdowns);
            
        
            try
            {
                if (ModelState.IsValid) { 
                var imagepath = await _imageUploader.UploadToTemporary(model.Image);
                var movieCreateDto = new MovieCreateDto(model.Name, model.Description, model.TicketPrice, imagepath,
                    model.StartDate, model.EndDate, model.MovieCategoryId, model.CinemaHallId,
                    model.ProducerId, model.ActorIds);
                await _movieService.Create(movieCreateDto);
                _notify.AddSuccessToastMessage("Movie Added Successfully");
                return RedirectToAction(nameof(Index));
                }
            }
            catch (Exception ex)
            {

                _logger.LogError(ex,ex.Message);
                _notify.AddErrorToastMessage(ex.Message);
            }
            return View(model);
        }
        public async Task<IActionResult> Update(int id)
        {
            try
            {
                var dropdowns = await GetDropdowns();
                SetDropdowns(dropdowns);
                var movie = await _unitOfWork.Movies.GetByIdAsync(id) ?? throw new MovieNotFoundException();
                var movieUpdateModel = new MovieUpdateViewModel() { 
                Id = movie.Id,
                Description = movie.Description,
                Name = movie.Name,
                TicketPrice = movie.TicketPrice,
                StartDate = movie.StartDate,
                EndDate = movie.EndDate,
                MovieCategoryId= movie.MovieCategoryId,
                CinemaHallId  =movie.CinemaHallId,
                ProducerId = movie.ProducerId,
                ImageSource = movie.Image,
                ActorIds= movie.ActorMovies.Where(a=>a.MovieId==movie.Id).Select(a=>a.ActorId).ToList()
                };
                return View(movieUpdateModel);

            }
            catch (Exception ex)
            {
                _logger.LogError(ex.Message);
                _notify.AddErrorToastMessage(ex.Message);
            }
            return RedirectToAction(nameof(Index));
        }

        [HttpPost]
        public async Task<IActionResult> Update(MovieUpdateViewModel model)
        {
            var dropdowns = await GetDropdowns();
            SetDropdowns(dropdowns);
            try
            {
                if(ModelState.IsValid)
                {
                    var imagepath = "";
                    if(model.Image != null &&model.Image.Length >0 )
                    {
                        imagepath = await _imageUploader.UploadToTemporary(model.Image);
                    }
                    var movieUpdateDto = new MovieUpdateDto(model.Id, model.Name, model.Description, model.TicketPrice, imagepath,
                        model.StartDate, model.EndDate, model.MovieCategoryId, model.CinemaHallId, model.ProducerId, model.ActorIds);
                    await _movieService.Update(movieUpdateDto);
                    _notify.AddSuccessToastMessage("Movie Updated Successfully");
                    return RedirectToAction(nameof(Index));
                }
            }
            catch (Exception  ex)
            {

                _logger.LogError(ex.Message);
                _notify.AddErrorToastMessage(ex.Message);
            }
            return View(model);
        }
        public async Task<IActionResult> Details(int id)
        {
            try
            {
                var movie = await _unitOfWork.Movies.GetByIdAsync(id) ?? throw new MovieNotFoundException();
                var movieDetailViewModel = new MovieDetailsViewModel
                {
                    Id = movie.Id,
                    Name = movie.Name,
                    Description = movie.Description,
                    MovieCategory = movie.Category.Name,
                    CinemaHall = movie.CinemaHall.Name,
                    Producer = movie.Producer.FullName,
                    StartDate = movie.StartDate.ToString("yyyy-MM-dd hh:mm tt"),
                    EndDate = movie.EndDate.ToString("yyyy-MM-dd hh:mm tt"),
                    ImageSource = movie.Image,
                    TicketPrice = movie.TicketPrice,
                    CinemaHallId = movie.CinemaHallId,
                    ProducerId = movie.ProducerId,
                    Status = movie.EndDate < DateTime.Now ? Movie.Expired :Movie.Available,
                    Actors = movie.ActorMovies.Where(a => a.MovieId == movie.Id).Select(b => new ActorModel
                    {
                        Id = b.Actor.Id,
                        Name = b.Actor.FullName,
                        Image = b.Actor.Image ?? ""
                    }).ToList()

                };
                return View(movieDetailViewModel);
            }
            catch (Exception ex)
            {
                _logger.LogError(ex.Message);
                _notify.AddErrorToastMessage(ex.Message);
            }
            return RedirectToAction(nameof(Index));
        }
        private static IQueryable<Movie> FilterMovies(MovieIndexViewModel model, IQueryable<Movie> movieQueryable)
        {
            if (model.CinemaId > 0)
            {
                movieQueryable = movieQueryable.Where(a => a.CinemaHallId == model.CinemaId);
            }
            if (model.ProducerId > 0)
            {
                movieQueryable = movieQueryable.Where(a => a.ProducerId == model.ProducerId);
            }
            if (model.CategoryId > 0)
            {
                movieQueryable = movieQueryable.Where(a => a.MovieCategoryId == model.CategoryId);
            }
            if (model.ActorId > 0)
            {
                movieQueryable = movieQueryable.Where(a => a.ActorMovies.Any(a => a.ActorId == model.ActorId));
            }

            return movieQueryable;
        }

        private async Task<DropDownViewModel> GetDropdowns()
        {
            var dropdowns = new DropDownViewModel() { 
            Actors = await _unitOfWork.Actors.GetQueryable().OrderBy(a=>a.FullName).ToListAsync(),
            Producers = await _unitOfWork.Producers.GetQueryable().OrderBy(a=>a.FullName).ToListAsync(),
            Categories = await _unitOfWork.Categories.GetQueryable().OrderBy(a=>a.Name).ToListAsync(),
            Cinemas = await _unitOfWork.CinemaHalls.GetQueryable().OrderBy(a=>a.Name).ToListAsync()
            };
            return dropdowns;
        }

        private void SetDropdowns(DropDownViewModel dropdowns)
        {
            ViewBag.Cinemas = new SelectList(dropdowns.Cinemas, "Id", "Name");
            ViewBag.Producers = new SelectList(dropdowns.Producers, "Id", "FullName");
            ViewBag.Actors = new SelectList(dropdowns.Actors, "Id", "FullName");
            ViewBag.Categories = new SelectList(dropdowns.Categories, "Id", "Name");
        }
    }
}

ETicketing/Views/Movie/Create.cshtml
@model ETicketing.ViewModels.Movie.MovieCreatViewModel

@{
    ViewData["Title"] = "Add a new movie";
}

<div class="row text">
    <div class="card col-md-12  ">

        <div class="col-md-12">
            <div class="card-header">
                <h4>@ViewData["Title"] </h4>
            </div>
            <div class="row">
                <div class="col-md-12 ">


                    <form asp-action="Create" enctype="multipart/form-data">
                        <div asp-validation-summary="ModelOnly" class="text-danger"></div>

                        <div class="row">
                            <div class="col-md-6">
                                <div class="form-group mt-1">
                                    <label asp-for="Name" class="control-label"></label>
                                    <input asp-for="Name" class="form-control" />
                                    <span asp-validation-for="Name" class="text-danger"></span>
                                </div>
                                <div class="form-group mt-2">
                                    <label asp-for="StartDate" class="control-label"></label>
                                    <input asp-for="StartDate" type="date" class="form-control" />
                                    <span asp-validation-for="StartDate" class="text-danger"></span>
                                </div>
                                <div class="form-group mt-2">
                                    <label asp-for="EndDate" class="control-label"></label>
                                    <input asp-for="EndDate" type="date" class="form-control" />
                                    <span asp-validation-for="EndDate" class="text-danger"></span>
                                </div>
                                <div class="form-group mt-2">
                                    <label asp-for="TicketPrice" class="control-label"></label>
                                    <input asp-for="TicketPrice" type="number" class="form-control" />
                                    <span asp-validation-for="TicketPrice" class="text-danger"></span>
                                </div>
                                 <div class="form-group mt-2">
                                    <label asp-for="CinemaHallId" class="control-label"></label>
                                    <select asp-for="CinemaHallId" class="form-control" asp-items="ViewBag.Cinemas" >
                                        <option value="">--select-</option>
                                    </select>
                                    <span asp-validation-for="CinemaHallId" class="text-danger"></span>
                                </div>
                                <div class="form-group mt-2">
                                    <label asp-for="MovieCategoryId" class="control-label"></label>
                                    <select asp-for="MovieCategoryId" class="form-control" asp-items="ViewBag.Categories">
                                        <option value="">--select-</option>
                                    </select>
                                    <span asp-validation-for="MovieCategoryId" class="text-danger"></span>
                                </div>
                                <div class="form-group mt-2">
                                    <label asp-for="ProducerId" class="control-label"></label>
                                    <select asp-for="ProducerId" class="form-control" asp-items="ViewBag.Producers">
                                        <option value="">--select-</option>
                                    </select>
                                    <span asp-validation-for="ProducerId" class="text-danger"></span>
                                </div>
                                 <div class="form-group mt-2">
                                    <label asp-for="ActorIds" class="control-label"></label>
                                    <select asp-for="ActorIds" class="form-control" asp-items="ViewBag.Actors" multiple>
                                         
                                    </select>
                                    <span asp-validation-for="ActorIds" class="text-danger"></span>
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="form-group text-center">
                                    <img id="ProfilePicturePreview" src="~/images/empty-profile.png" class="border-info rounded-circle" style="width: 200px; height:200px" />
                                </div>
                                <div class="form-group">
                                    <label asp-for="Image" class="control-label"></label>
                                    <input asp-for="Image" class="form-control" type="file" id="file" />
                                    <span asp-validation-for="Image" class="text-danger"></span>
                                </div>
                               <div class="form-group mt-2">
                                    <label asp-for="Description" class="control-label"></label>
                                    <textarea asp-for="Description" class="form-control" rows="13"></textarea>
                                    <span asp-validation-for="Description" class="text-danger"></span>
                                </div>
                               

                            </div>
                          
                        </div>



                        <div class="card-footer text-muted  mt-2">
                            <button type="submit" class="btn btn-outline-success float-right"><i class="bi bi-check-circle-fill"></i> Create</button>
                            <a class="btn btn-outline-secondary" asp-action="Index"><i class="bi bi-arrow-left-circle-fill"></i> Back</a>
    </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

@section Scripts{
<script>

    $("#file").on("change",function () {
        readURL(this);
    });
    function readURL(input) {

        if (input.files && input.files[0]) {
            var reader = new FileReader();

            reader.onload = function (e) {
                $('#ProfilePicturePreview').attr('src', e.target.result);
            };
            reader.readAsDataURL(input.files[0]);
        }
    }
</script>
}

ETicketing/Views/Movie/Details.cshtml
@model ETicketing.ViewModels.Movie.MovieDetailsViewModel
@using CoreModule.Source.Entity

@{
    ViewData["Title"] = "Movie details";
}

<div class="row">
    <div class="col-md-12">
        <div class="card mb-12">
            <div class="row g-0">
               
                <div class="col-md-4">
                    <img class="image_fit_all" src="~/images/uploads/@Model.ImageSource" onerror="this.onerror=null;this.src='/images/empty-profile.png';" width="100%"height="100%" alt="@Model.Name">
                </div>
                <div class="col-md-8">
                    <div class="card-body">
                          <p class="card-text"><b>Movie : @Model.Name</b></p>
                        <p class="card-text">@Model.Description</p>
                        <p class="card-text">
                            <b>Cinema: </b>
                            <a asp-controller="CinemaHall" asp-action="Details" asp-route-id="@Model.CinemaHallId">
                                @Model.CinemaHall
                            </a>
                        </p>
                        <p class="card-text">
                            <b>Producer: </b>
                            <a asp-controller="Producer" asp-action="Details" asp-route-id="@Model.ProducerId">
                                @Model.Producer
                            </a>
                        </p>
                        <p class="card-text"><b>Category: </b>@Model.MovieCategory</p>
                        <p class="card-text"><b>Start Date: </b>@Model.StartDate</p>
                        <p class="card-text"><b>End Date: </b>@Model.EndDate</p>
                        <p class="card-text ">
                            <b>Status: </b>
                            @if (Model.Status == Movie.Available)
                            {
                                <span class="badge bg-success text-white">@Model.Status</span>
                            }
                          
                            else
                            {
                                <span class="badge bg-danger text-white">@Model.Status</span>
                            }
                        </p>
                        <p class="card-text">
                            <b>Actors: </b>
                            <hr />
                            <div class="row">
                                @foreach (var actor in Model.Actors)
                                {
                                    <div class="col-md-3 text-center">
                                        <img class="image__fit border-info rounded-circle" src="~/images/uploads/@actor.Image" onerror="this.onerror=null;this.src='/images/empty-profile.png';"
                                        style="width: 100px;height:100px;" />
                                        <br />
                                        <a asp-controller="Actor" asp-action="Details" asp-route-id="@actor.Id">@actor.Name</a>
                                    </div>
                                }
                            </div>
                        </p>

                    </div>
                </div>
                <div class="col-md-12">
                    <div class="card-footer">
                        <p class="card-text">
                            <a class="btn btn-outline-primary float-right" asp-action="Index">
                                Back to List
                            </a>
                                                   </p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

ETicketing/Views/Movie/Index.cshtml
@model ETicketing.ViewModels.Movie.MovieIndexViewModel
@using CoreModule.Source.Entity;
@{
    ViewData["Title"] = "List of Movies";

}

<div class="row">
    <div class="card">
        <h5 class="card-header bg-primary text-white">@ViewData["Title"]</h5>
        <div class="card-body">
            <form asp-coontroller="movie" asp-action="Index">
                <div class="row">

                    <div class="form-group col-md-2">
                        <label asp-for="ProducerId" class="control-label">By Producer</label>
                        <select asp-for="ProducerId" class="form-control" asp-items="ViewBag.Producers">
                            <option value=0>All</option>
                        </select>
                    </div>
                    <div class="form-group col-md-2">
                        <label asp-for="CategoryId" class="control-label">By Category</label>
                        <select asp-for="CategoryId" class="form-control" asp-items="ViewBag.Categories">
                            <option value=0>All</option>
                        </select>
                    </div>
                    <div class="form-group col-md-2">
                        <label asp-for="ActorId" class="control-label">By Actor</label>
                        <select asp-for="ActorId" class="form-control" asp-items="ViewBag.Actors">
                            <option value=0>All</option>
                        </select>
                    </div>
                    <div class="form-group col-md-2">
                        <label asp-for="CinemaId" class="control-label">By Cinema</label>
                        <select asp-for="CinemaId" class="form-control" asp-items="ViewBag.Cinemas">
                            <option value=0>All</option>
                        </select>
                    </div>
                    <div class="form-group col-md-2 mt-4">
                        <button type="submit" class="btn btn-secondary btn-sm"><i class="bi bi-filter"></i> Filter</button>
                    </div>
                </div>
            </form>

            <div class="row mt-4">
            <div class=col-md-12 >
                <a class="btn-info btn btn-sm text-white" asp-controller="Movie" asp-action="Create">  <i class="bi bi-plus-circle"></i> Add</a>
            </div>
            
            <div class="col-md-12 mt-2 ">

                <table class=table table-borderless>
                    <thead>
                        <tr class="card-header">
                            <th>Image</th>
                            <th> Name</th>
                            <th> Category</th>
                            <th>Cinema</th>
                            <th>Start Date</th>
                            <th>End Date</th>
                            <th>Ticket Price</th>
                            <th>Status</th>                          
                            <th>Actions</th>
                        </tr>
                    </thead>
                    <tbody>
                        @if (Model.MovieDatas.Any())
                        {
                            @foreach (var item in Model.MovieDatas)
                            {
                                <tr>
                                    <td >
                                        <img class="rounded-circle image__fit" src="~/images/uploads/@item.Image" onerror="this.onerror=null;this.src='/images/empty-profile.png';" alt="@item.Name" style="width: 100px;height:100px" />
                                    </td>
                                    <td >
                                        @Html.DisplayFor(modelItem => item.Name)
                                    </td>
                                     <td >
                                        @Html.DisplayFor(modelItem => item.MovieCategory)
                                    </td>
                                    <td >
                                        @Html.DisplayFor(modelItem => item.CinemaHall)
                                    </td>
                                    <td >
                                        @Html.DisplayFor(modelItem => item.StartDate)
                                    </td>
                                    <td >
                                        @Html.DisplayFor(modelItem => item.EndDate)
                                    </td>
                                    <td >
                                        <span> Rs. @item.TicketPrice</span>
                                    </td>
                                    <td >
                                        @if (item.Status == Movie.Available)
                                        {
                                            <span class="text-success"> @item.Status</span>
                                        }
                                        else
                                        {
                                            <span class="text-danger">  @item.Status</span>
                                        }

                                    </td>
                                 
                                    <td >
                                        <a class="btn btn-outline-primary btn-sm" asp-action="Update" asp-route-id="@item.Id"><i class="bi bi-pencil-square"></i>Edit </a> |
                                        <a class="btn btn-outline-info btn-sm" asp-action="Details" asp-route-id="@item.Id"><i class="bi bi-eye"></i>Details </a>
                                    </td>


                                </tr>
                            }
                        }
                        else
                        {
                            <tr>
                                <td colspan="8" class="text-center align-middle"> <h4>No movies added yet</h4></td>
                            </tr>
                        }
                    </tbody>

                </table>
                <div class="card-footer text-muted">
                </div>
            </div>
            </div>
        </div>
    </div>
</div>