ETicketing/Controllers/ActorController.cs
using CoreModule.Source.Dto.Actor;
using CoreModule.Source.Entity;
using CoreModule.Source.Exceptions;
using CoreModule.Source.Service;
using CoreModule.Source.Service.Image;
using CoreModule.UOW;
using ETicketing.Extensions;
using ETicketing.ViewModels.Actor;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using NToastNotify;

namespace ETicketing.Controllers
{
 [Authorize(Roles =ApplicationUser.RoleAdmin)]
    public class ActorController : Controller
    {
        private readonly UnitOfWorkInterface _unitOfWork;
        private readonly ILogger<ActorController> _logger;
        private readonly IToastNotification _notify;
        private readonly ActorServiceInterface _actorService;
        private readonly ImageUploaderInterface _imageUploader;
        public ActorController(UnitOfWorkInterface unitOfWork,
            ILogger<ActorController> logger,
            IToastNotification notify,
            ActorServiceInterface actorService,
            ImageUploaderInterface imageUploader)
        {
            _unitOfWork = unitOfWork;
            _logger = logger;
            _notify = notify;
            _actorService = actorService;
            _imageUploader = imageUploader;
        }
        public async Task<IActionResult> Index()
        {
          var user=  await this.GetCurrentUser();
            var actors = await _unitOfWork.Actors.GetAllAsync();
            var actorIndexViewModel = actors.Select(a => new ActorIndexViewModel
            {
                Id = a.Id,
                Name = a.FullName,
                Description = a.Description,
                Image = a.Image ?? ""
            });
            return View(actorIndexViewModel);
        }
        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(ActorCreateViewModel model)
        {
            try
            {
                if(ModelState.IsValid)
                {
                    string? imagePath = await ValidateAndUploadImage(model.Image);
                    var createDto = new ActorCreateDto(model.Name, model.Description, imagePath);
                    await _actorService.Create(createDto);
                    _notify.AddSuccessToastMessage("Actor Added Successfully");
                    return RedirectToAction(nameof(Index));
                }
            }
            catch (Exception ex)
            {

                _logger.LogError(ex.Message);
                _notify.AddErrorToastMessage(ex.Message);
            }
            return View(model);
        }

        [HttpGet]
        public async Task<IActionResult> Update(int id)
        {
            try
            {
                var actor = await _unitOfWork.Actors.GetByIdAsync(id) ?? throw new ActorNotFoundException();
                var updateViewModel = new ActorUpdateViewModel
                {
                    Id = actor.Id,
                    Name = actor.FullName,
                    Description = actor.Description,
                    ImageSource = actor.Image
                };
                return View(updateViewModel);
            }
            catch (Exception ex)
            {
                _logger.LogError(ex.Message);
                _notify.AddErrorToastMessage(ex.Message);
            }
            return RedirectToAction(nameof(Index));
        }

        [HttpPost]
        public async Task<IActionResult> Update(ActorUpdateViewModel model)
        {
            try
            {
                if(ModelState.IsValid)
                {
                    string? imagePath = await ValidateAndUploadImage(model.Image);
                    var updateDto = new ActorUpdateDto(model.Id, model.Name, model.Description, imagePath);
                    await _actorService.Update(updateDto);
                    return RedirectToAction(nameof(Index));
                }
            }
            catch (Exception ex)
            {

                _logger.LogError(ex.Message);
                _notify.AddErrorToastMessage(ex.Message);
            }
            return View(model);
        }
        public async Task<IActionResult> Details(int id)
        {
            try
            {
                var actor = await _unitOfWork.Actors.GetByIdAsync(id) ?? throw new ActorNotFoundException();
                ActorDetailsViewModel actorDetailsViewModel = ConfigureActorDetails(actor);
                return View(actorDetailsViewModel);
            }
            catch (Exception ex)
            {
                _logger.LogError(ex.Message);
                _notify.AddErrorToastMessage(ex.Message);
            }
            return RedirectToAction(nameof(Index));
        }

      [HttpGet]
        public async Task<IActionResult> Delete(int id)
        {
           
            await _actorService.Remove(id);
            return RedirectToAction(nameof(Index));
        }

        private async Task<string> ValidateAndUploadImage(IFormFile file)
        {
            string? imagePath = null;
            if (file != null &&file.Length > 0)
            {
                imagePath = await _imageUploader.UploadToTemporary(file);
            }

            return imagePath;
        }
        private static ActorDetailsViewModel ConfigureActorDetails(CoreModule.Source.Entity.Actor actor)
        {
            return new ActorDetailsViewModel
            {
                id = actor.Id,
                Name = actor.FullName,
                Description = actor.Description,
                Image = actor.Image ?? ""
            };
        }
    }
}

ETicketing/Controllers/CartController.cs
using CoreModule.UOW;
using ETicketing.Extensions;
using ETicketing.ViewModels.Cart;
using Microsoft.AspNetCore.Mvc;

namespace ETicketing.Controllers
{
    public class CartController : Controller
    {
        private readonly UnitOfWorkInterface _unitOfWork;
        private readonly ILogger<CartController> _logger;
        public CartController(UnitOfWorkInterface unitOfWork,
            ILogger<CartController> logger)
        {
            _unitOfWork = unitOfWork;
            _logger = logger;
        }
        public async Task<IActionResult> Index()
        {
            return View();
        }

        public async Task<IActionResult> LoadCartPartialView()
        {
            try
            {
                var userId = this.GetCurrentUserId();
                var cartList = await _unitOfWork.CartItems.GetByUserId(userId);
                var cartListIndexModel = cartList.Select(a => new CartIndexViewModel
                {
                    Id = a.Id,
                    MovieName = a.Movie.Name,
                    Cinema = a.Movie.CinemaHall.Name,
                    Quantity = a.Quantity,
                    Rate = a.Rate,
                    Total = a.TotalAmount

                }).ToList();
                return PartialView("_cartListPartialView", cartListIndexModel);
            }
            catch (Exception ex)
            {
                _logger.LogError(ex.Message);
                return BadRequest(ex.Message);
            }
           
        }

    }
}

ETicketing/Controllers/OrderController.cs
using CoreModule.Source.Entity;
using CoreModule.UOW;
using ETicketing.Extensions;
using ETicketing.ViewModels.Order;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using NToastNotify;

namespace ETicketing.Controllers
{
    public class OrderController : Controller
    {
        private readonly UnitOfWorkInterface _unitOfWork;
        private readonly ILogger<OrderController> _logger;
        private readonly IToastNotification _notify;
        private readonly UserManager<ApplicationUser> _userManager;
        public OrderController(UnitOfWorkInterface unitOfWork,
            ILogger<OrderController> logger,
            IToastNotification notify,
            UserManager<ApplicationUser> userManager)
        {
            _unitOfWork = unitOfWork;
            _logger = logger;
            _notify = notify;
            _userManager = userManager;
        }
        public async Task<IActionResult> Index()
        {
            var user = await _unitOfWork.Users.GetByIdString(this.GetCurrentUserId());
            var orderQueryable = _unitOfWork.Orders.GetQueryable();
            if(await _userManager.IsInRoleAsync(user,ApplicationUser.RoleUser))
            {
                orderQueryable = orderQueryable.Where(a => a.UserId == this.GetCurrentUserId());
            }
            var orderIndexViewModel = await orderQueryable.Select(a => new OrderIndexViewModel
            {
                Id = a.Id,
                User = a.User.FullName,
                Status = a.Status,
                CreatedOn = a.CreatedOn.ToString("yyyy-MM-dd")
            }).ToListAsync();
            return View(orderIndexViewModel);
        }

        public async Task<IActionResult> Details(int id)
        {
            try
            {
                var order = await _unitOfWork.Orders.GetByIdAsync(id) ?? throw new Exception("Order Not Found");
                var orderDetailViewModel = new OrderDetailViewModel() {
                    Id = order.Id,
                    User = order.User.FullName,
                    Status = order.Status,
                    CreatedOn = order.CreatedOn.ToString("yyyy-MM-dd"),
                    OrderItems = order.OrderItems.Select(a => new OrderItemViewModel
                    {
                        Movie = a.Movie.Name,
                        Cinema = a.Movie.CinemaHall.Name,
                        Quantity = a.Quantity,
                        TicketPrice = a.Rate,
                        Amount = a.Amount
                    }).ToList(),
                    ShippingAddress= new ShippingAddressViewModel
                    {
                        Name = order.ShippingAddress.FullName,
                        Address = order.ShippingAddress.Address,
                        ZipCode = order.ShippingAddress.ZipCode,
                        PhoneNumber = order.ShippingAddress.PhoneNumber,
                    }

                };
                return View(orderDetailViewModel);

            }
            catch (Exception ex)
            {

                _notify.AddErrorToastMessage(ex.Message);
                _logger.LogError(ex.Message);
            }
            return RedirectToAction(nameof(Index));
        }
    }
}

ETicketing/Controllers/UserController.cs
using CoreModule.Source.Entity;
using CoreModule.Source.Exceptions;
using CoreModule.UOW;
using ETicketing.ViewModels.User;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using NToastNotify;

namespace ETicketing.Controllers
{
    [Authorize(Roles = ApplicationUser.RoleAdmin)]
    public class UserController : Controller
    {
        private readonly ILogger<UserController> _logger;
        private readonly UnitOfWorkInterface _unitOfWork;
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly IToastNotification _notify;
        public UserController(ILogger<UserController> logger,
            UnitOfWorkInterface unitOfWork,
            UserManager<ApplicationUser> userManager,
            IToastNotification notify)
        {
            _logger = logger;
            _unitOfWork = unitOfWork;
            _userManager = userManager;
            _notify = notify;
        }
      
        public async Task<IActionResult> Index()
        {
            var users = await _userManager.Users.ToListAsync();

            var userIndexViewModel = new List<UserIndexViewModel>();
            foreach (var user in users)
            {
               
                var userModel =  new UserIndexViewModel
                {
                    Id = user.Id,
                    Name = user.FullName,
                    Email = user.Email,
                    Username = user.UserName,
                    Status = await _userManager.IsInRoleAsync(user, ApplicationUser.RoleAdmin) ? ApplicationUser.RoleAdmin : ApplicationUser.RoleUser
                };
                userIndexViewModel.Add(userModel);
            }
            return View(userIndexViewModel);
            

        }

        public IActionResult ChangePassword(string userId)
        {
            var changePasswordViewModel = new ChangePasswordVieModel() { 
            UserId = userId
            };

            return View(changePasswordViewModel);
        }

        [HttpPost]
        public async Task<IActionResult> ChangePassword(ChangePasswordVieModel model)
        {
            try
            {
                var user = await _userManager.FindByIdAsync(model.UserId) ?? throw new UserNotFoundException();
                var isPasswordChanged = await _userManager.ChangePasswordAsync(user, model.OldPassword, model.NewPassword);
                if(isPasswordChanged.Succeeded)
                {
                    _notify.AddSuccessToastMessage("Password Changed Successfully");
                    return RedirectToAction(nameof(Index));
                }
                foreach(var error in isPasswordChanged.Errors)
                {
                    ModelState.AddModelError("error", error.Description);
                }
            }
            catch (Exception ex)
            {
                _logger.LogError(ex.Message);
                _notify.AddErrorToastMessage(ex.Message);
            }
            return View(model);
        }
    }
}

ETicketing/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Cinema App</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/ETicketing.styles.css" asp-append-version="true" />
   <link href="https://fonts.googleapis.com/css2?family=Lato:wght@300&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.4.1/font/bootstrap-icons.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jquery-confirm/3.3.2/jquery-confirm.min.css">
    <style>
        body {
            font-family: 'Lato', sans-serif;
        }
    </style>
      @await RenderSectionAsync("Styles", false)
</head>

<body class="d-flex flex-column min-vh-100" style="background-color:#fcfcfa">
    @await Html.PartialAsync("_navbar")
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    @await Html.PartialAsync("_footer")
    @await Component.InvokeAsync("NToastNotify")
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/lib/jquery-validation/dist/jquery.validate.min.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-confirm/3.3.2/jquery-confirm.min.js"></script>
    <script src="//cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

ETicketing/Views/Shared/_footer.cshtml
 <footer class="border-top footer text-muted mt-auto">
        <div class="container">
            &copy; 2022 - Cinema App
        </div>
    </footer>

ETicketing/Views/Shared/_header.cshtml
@using CoreModule.Source.Entity
@using Microsoft.AspNetCore.Identity
@inject UserManager<ApplicationUser> UserManager;
@if (!User.Identity.IsAuthenticated)
{

    <a class="btn btn-outline-success my-2 my-sm-0" asp-controller="Account" asp-action="Login">
        <i class="bi bi-box-arrow-in-right"></i> Log in
    </a>
    <span style="padding: 5px;"></span>

    <a class="btn btn-outline-primary my-2 my-sm-0" asp-controller="Account" asp-action="Register">
        <i class="bi bi-person-plus"></i> Register
    </a>
}

else
{
    <div class="dropdown">
        <a class=" dropdown-toggle nav-link" data-bs-toggle="dropdown">
            <i class="bi bi-person-badge"></i>   Hello @User.Identity.Name
        </a>
        <ul class="dropdown-menu">
            <li>
                <a class="dropdown-item" asp-controller="Order" asp-action="Index"><i class="bi bi-basket-fill"></i> Orders</a>

            </li>
            @if (User.IsInRole("Admin"))
            {
                <li>
                    <a class="dropdown-item" asp-controller="User" asp-action="Index"><i class="bi bi-person-circle"></i> Users</a>
                </li>
            }
              <li>
                <a class="dropdown-item" asp-controller="Account" asp-action="ChangePassword"><i class="bi bi-lock"></i> Change Password</a>

            </li>

        </ul>
    </div>


    <span style="padding: 5px;"></span>
    <form asp-controller="Account" asp-action="Logout">
        <button class="btn btn-outline-danger my-2 my-sm-0">
            <i class="bi bi-box-arrow-in-right"></i> Log out
        </button>
    </form>
}

ETicketing/Views/Shared/_navbar.cshtml
<header>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3 navbar-fixed-top">
        <div class="container-fluid">
            <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Cinema App</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                <ul class="navbar-nav flex-grow-1">
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index"><i class="bi bi-film"></i> Home</a>

                    </li>

                    @if (User.Identity.IsAuthenticated && User.IsInRole("Admin"))
                    {
                        <li class="nav-item">
                            <div class="dropdown">
                                <a class=" dropdown-toggle nav-link" data-bs-toggle="dropdown">
                                    <i class="bi bi-gear"></i>   Management
                                </a>
                                <ul class="dropdown-menu">
                                    <li>
                                        <a class="dropdown-item" asp-controller="MovieCategory" asp-action="Index"><i class="bi bi-ui-checks-grid"></i> Category</a>

                                    </li>
                                    <li>
                                        <a class="dropdown-item" asp-controller="CinemaHall" asp-action="Index"><i class="bi bi-camera-reels"></i> Cinemas</a>
                                    </li>
                                    <li>
                                        <a class="dropdown-item" asp-controller="Producer" asp-action="Index"><i class="bi bi-headset"></i> Producer</a>
                                    </li>
                                    <li>
                                        <a class="dropdown-item" asp-controller="Actor" asp-action="Index"><i class="bi bi-person-square"></i> Actor</a>
                                    </li>
                                    <li>
                                        <a class="dropdown-item" asp-controller="Movie" asp-action="Index"><i class="bi bi-camera-video"></i> Movies</a>
                                    </li>
                                </ul>
                            </div>
                        </li>
                    }
                </ul>


                <form class="d-flex" asp-controller="Home" asp-action="Index" >
                    <input class="form-control me-2" type="search" placeholder="by name/category" name="searchString" aria-label="Search">
                    <button class="btn btn-outline-success" type="submit"><i class="bi bi-search"></i></button> &nbsp;
                </form>
                @if(User.Identity.IsAuthenticated)
                {
                <ul class="navbar-nav">
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-controller="Cart" asp-action="Index">
                            <i class="bi bi-cart4"></i> <span id="cartCount"></span>
                        </a>
                    </li>
                </ul>
                }
                @await Html.PartialAsync("_header")
            </div>
        </div>
    </nav>
</header>