ETicketing/ViewModels/Cart/CartIndexViewModel.cs
namespace ETicketing.ViewModels.Cart
{
    public class CartIndexViewModel
    {
        public int Id { get; set; }
        public string MovieName { get; set; }
        public string Cinema { get; set; }
        public int Quantity { get; set; }
        public decimal Rate { get; set; }
        public decimal Total { get; set; }
        public decimal GrandTotal { get; set; }
    }
}

ETicketing/Controllers/CartController.cs
using CoreModule.UOW;
using ETicketing.Extensions;
using ETicketing.ViewModels.Cart;
using Microsoft.AspNetCore.Mvc;

namespace ETicketing.Controllers
{
    public class CartController : Controller
    {
        private readonly UnitOfWorkInterface _unitOfWork;
        private readonly ILogger<CartController> _logger;
        public CartController(UnitOfWorkInterface unitOfWork,
            ILogger<CartController> logger)
        {
            _unitOfWork = unitOfWork;
            _logger = logger;
        }
        public async Task<IActionResult> Index()
        {
            return View();
        }

        public async Task<IActionResult> LoadCartPartialView()
        {
            try
            {
                var userId = this.GetCurrentUserId();
                var cartList = await _unitOfWork.CartItems.GetByUserId(userId);
                var cartListIndexModel = cartList.Select(a => new CartIndexViewModel
                {
                    Id = a.Id,
                    MovieName = a.Movie.Name,
                    Cinema = a.Movie.CinemaHall.Name,
                    Quantity = a.Quantity,
                    Rate = a.Rate,
                    Total = a.TotalAmount

                }).ToList();
                return PartialView("_cartListPartialView", cartListIndexModel);
            }
            catch (Exception ex)
            {
                _logger.LogError(ex.Message);
                return BadRequest(ex.Message);
            }
           
        }

    }
}

ETicketing/Controllers/CheckoutController.cs
using CoreModule.UOW;
using ETicketing.Extensions;
using ETicketing.ViewModels.Cart;
using Microsoft.AspNetCore.Mvc;

namespace ETicketing.Controllers
{
    public class CheckoutController : Controller
    {
        private readonly UnitOfWorkInterface _unitOfWork;
        private readonly ILogger<CheckoutController> _logger;
        public CheckoutController(UnitOfWorkInterface unitOfWork,
            ILogger<CheckoutController> logger)
        {
            _unitOfWork = unitOfWork;
            _logger = logger;
        }
        public async Task<IActionResult> Index()
        {
            var userId = this.GetCurrentUserId();
            var cartList = await _unitOfWork.CartItems.GetByUserId(userId);
            var cartListIndexModel = cartList.Select(a => new CartIndexViewModel
            {
                Id = a.Id,
                MovieName = a.Movie.Name,
                Cinema = a.Movie.CinemaHall.Name,
                Quantity = a.Quantity,
                Rate = a.Rate,
                Total = a.TotalAmount

            }).ToList();
            return View(cartListIndexModel);
        }
        public IActionResult Success(int orderId)
        {
            return View(orderId);
        }
    }
}

ETicketing/Views/Cart/Index.cshtml
@{

}

<div id="cartDiv">

</div>

@section scripts{
    <script>
        $(document).ready(function(){
            LoadCartList();
        });

      function LoadCartList() {
        $.ajax({
            url: '@Url.Action("LoadCartPartialView", "Cart")',
            contentType: 'application/html; charset=utf-8',
            type: 'GET',
            dataType: 'html',
            success: function (result) {
                console.log(result)
                $('#cartDiv').html(result);
            },
            error: function (errorResponse) {
                Swal.fire({
                          title: 'Error!',
                          text: "Error loading cart item",
                          icon: 'error',
                         showConfirmButton: false,
                          timer: 1500
                        });
               
            }
        });
      
        }


      function continueShopping() {
        window.open("/Home/Index", "_self");
    }

     function increaseQuantity(item) {
        event.preventDefault();
        var cartItemId = $(item).closest("td").find("div#itemId").attr("data-itemId");
        var Url = "/api/carts/" + cartItemId + "/increasequantity";

           $.ajax({
            url:Url ,
            contentType: 'application/json; charset=utf-8',
            type: 'patch',
            dataType: 'json',
            success: function (result) {
                LoadCartList();
               
            },
            error: function (errorResponse) {
                console.log(errorResponse)
               Swal.fire({
                          title: 'Error!',
                          text: "Error increasing item",
                          icon: 'error',
                         showConfirmButton: false,
                          timer: 1500
                        });
                LoadCartList();
            }
        });

    }

      function decreaseQuantity(item) {
        event.preventDefault();
        var cartItemId = $(item).closest("td").find("div#itemId").attr("data-itemId");
        var Url = "/api/carts/" + cartItemId + "/decreasequantity";

           $.ajax({
            url:Url ,
            contentType: 'application/json; charset=utf-8',
            type: 'patch',
            dataType: 'json',
            success: function (result) {
                LoadCartList();
               
            },
            error: function (errorResponse) {
                 Swal.fire({
                          title: 'Error!',
                          text: "Error decreasing item",
                          icon: 'error',
                         showConfirmButton: false,
                          timer: 1500
                        });
                LoadCartList();
            }
        });

    }

      function updateQuantity(item) {

           event.preventDefault();
           var qty = $(item).val();
          var cartItemId = $(item).closest("td").find("div#itemId").attr("data-itemId");
           var Url = "/api/carts/" + cartItemId + "/updateQuantity";
           var data =
           {
               Quantity: qty
           };
           $.ajax({
            url:Url ,
            contentType: 'application/json; charset=utf-8',
            type: 'put',
             dataType: 'json',
             data: JSON.stringify(data),
            success: function (result) {
                LoadCartList();
            },
            error: function (errorResponse) {
                console.log(errorResponse);
                Swal.fire({
                          title: 'Error!',
                          text: "Error updating item",
                          icon: 'error',
                         showConfirmButton: false,
                          timer: 1500
                        });
             
               LoadCartList();
            }
        });
    }

        function removeItem(item) {
           event.preventDefault();
           var qty = $(item).val();
          var cartItemId = $(item).closest("td").find("div#itemId").attr("data-itemId");
           var Url = "api/carts/" + cartItemId ;

           $.ajax({
            url:Url ,
            contentType: 'application/json; charset=utf-8',
            type: 'Delete',
             dataType: 'json',
           
               success: function (result) {
                   loadCartCount();
               LoadCartList();
              
               
            },
            error: function (errorResponse) {
                 Swal.fire({
                          title: 'Error!',
                          text: "Error removing item",
                          icon: 'error',
                         showConfirmButton: false,
                          timer: 1500
                        });
               LoadCartList();
             
            }
        });
    }


    </script>
}

ETicketing/Views/Cart/_cartListPartialView.cshtml
@model IEnumerable<ETicketing.ViewModels.Cart.CartIndexViewModel>


@{
    ViewData["Title"] = "Ticket cart summary";
}
   <h5 class="card-header text-black">@ViewData["Title"]</h5>
    @if (Model.Any())
    {

        <section class="cart-section section-padding">
            <div class="container">

                <div class="row mt-4">

                    <div class="col-md-12 col-lg-8">
                        <div class="table-wrapper bg-primary-offset bg-offset">
                            <table class="table table-det table-mob-responsive">
                                <thead>
                                    <tr class="card-header bg-secondary text-white">
                                        <th colspan="2">Particulars</th>
                                        <th>Amount</th>
                                    </tr>
                                </thead>
                                <tbody>

                                    @foreach (var cartItem in Model)
                                    {
                                        <tr >
                                           
                                            <td>
                                                <div id="itemId" data-itemId="@cartItem.Id"></div>
                                                <div class="d-block font-weight-bold mb-2"></div>
                                                <div class="mb-2 font-weight-bold text-secondary">@cartItem.MovieName (Cinema :@cartItem.Cinema)</div>
                                                <div class="cart-operation">
                                                    @if (cartItem.Quantity > 1)
                                                    {
                                                        <button onclick="decreaseQuantity(this)" class="btn"><i class="bi bi-node-minus"></i></button>
                                                    }
                                                    else
                                                    {
                                                        <button class="btn "><i class="bi bi-node-minus"></i></button>
                                                    }
                                                    <input onchange="updateQuantity(this)" type="text" min="1" pattern="[1-9]+" onkeypress="return event.charCode >= 48 && event.charCode <= 57" class="text-center" value="@cartItem.Quantity" />
                                                    <button onclick="increaseQuantity(this)" class="btn"><i class="bi bi-plus-circle"></i></button>

                                                </div>
                                                <button onclick="removeItem(this)" class="remove-cart-items btn btn-sm text-danger" data-itemId="@cartItem.Id">Remove</button>
                                            </td>
                                            <td>
                                                <div class="d-block"> Rate Rs. @cartItem.Rate </div>
                                                <div class="d-none d-lg-block mb-2"> Qty: @cartItem.Quantity</div>
                                                <div class="d-none d-lg-block font-weight-bold">Total : Rs. @cartItem.Total</div>
                                            </td>
                                        </tr>


                                    }


                                </tbody>
                            </table>
                        </div>
                    </div>
                    <div class="col-12 col-md-6 col-lg-4">
                        <div class="table-wrapper bg-offset">
                            <table class="table table-calc">
                                <thead>
                                    <tr class="card-header bg-secondary text-white">
                                        <th colspan="2">
                                            <span class="font-weight-bold d-block">Summary</span>

                                        </th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach (var cartItem in Model)
                                    {
                                        <tr>
                                            <td>@cartItem.MovieName</td>
                                            <td>Rs @cartItem.Total</td>
                                        </tr>

                                    }

                                </tbody>
                                <tfoot>
                                    <tr class="card-footer">
                                        <td class="text-primary-color font-weight-bold text-uppercase">Total</td>
                                        <td>RS @Model.Sum(a=>a.Total)</td>
                                    </tr>
                                </tfoot>
                            </table>
                            <div class="btn-wrap mt-5">

                                <a asp-controller="Checkout" asp-action="Index" class="btn btn-success"><i class="bi bi-check2-all"></i> Proceed To Checkout</a>

                            </div>
                            <button class="btn pull-right btn-sm " onclick="continueShopping(this)"><u class="text-primary">Continue booking....</u></button>
                        </div>
                    </div>
               
                </div>
            </div>
        </section>

    }
    else
    {
        <section class="section-padding thankyou-section mt-4">
            <div class="container bootstap-def">
                <div class="row justify-content-center">
                    <div class="col-12 col-lg-10 text-center">
                        <span class="d-block icon">
                            <i class="ion ion-md-cart text-warning"></i>
                        </span>
                        <h1 class="section-heading text-primary">Your Cart is Empty </h1>
                        <i class="bi bi-cart-x text-danger" style="font-size:100px"> </i>
                        <p>Looks like you haven't added anything to cart yet.</p>
                    </div>
                    <div class="btn-wrap mt-1">

                        <a onclick="continueShopping(this)" class="btn  rectangle w-100 pt-3 pb-3 text-white"><h4 class="bg-primary">Continue Shopping........</h4></a>

                    </div>
                </div>
            </div>
        </section>
    }