ETicketing/ViewModels/MovieCategory/MovieCategoryViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace ETicketing.ViewModels.MovieCategory
{
    public class MovieCategoryIndexViewModel
    {
        public int Id { get; set; }
        public string Name { get; set; }
    }
    public class MovieCategoryCreateViewModel
    {
        [Required(ErrorMessage ="Name is required")]
        public string Name { get; set; }
    }
    public class MovieCategoryUpdateViewModel : MovieCategoryCreateViewModel
    {
        public int Id { get; set; }
    }


}

ETicketing/Controllers/MovieCategoryController.cs
using CoreModule.Source.Dto.MovieCategory;
using CoreModule.Source.Entity;
using CoreModule.Source.Exceptions;
using CoreModule.Source.Service;
using CoreModule.UOW;
using ETicketing.ViewModels.MovieCategory;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using NToastNotify;

namespace ETicketing.Controllers
{
    [Authorize(Roles = ApplicationUser.RoleAdmin)]
    public class MovieCategoryController : Controller
    {
        private readonly UnitOfWorkInterface _unitOfWork;
        private readonly ILogger<MovieCategoryController> _logger;
        private readonly MovieCategoryServiceInterface _movieCategoryService;
        private readonly IToastNotification _notify;
        public MovieCategoryController(UnitOfWorkInterface unitOfWork,
            MovieCategoryServiceInterface movieCategoryService,
            ILogger<MovieCategoryController> logger,
            IToastNotification notify)
        {
            _unitOfWork = unitOfWork;
            _logger = logger;
            _movieCategoryService = movieCategoryService;
            _notify = notify;
        }
        public async Task<IActionResult> Index()
        {
            var movieCategoryList = await _unitOfWork.Categories.GetAllAsync();
            var movieCategoryIndexViewModel = movieCategoryList.Select(a => new MovieCategoryIndexViewModel
            {
                Id = a.Id,
                Name = a.Name
            });
            return View(movieCategoryIndexViewModel);
        }

        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Create(MovieCategoryCreateViewModel model)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    var movieCategoryCreateDto = new MovieCategoryCreateDto(model.Name);
                    await _movieCategoryService.Create(movieCategoryCreateDto);
                    _notify.AddSuccessToastMessage("Category Created Successfully");
                    return RedirectToAction(nameof(Index));
                }

            }
            catch (Exception ex)
            {

                _notify.AddErrorToastMessage(ex.Message);
                _logger.LogError(ex,ex.Message);
            }
            return View(model);
        }

        public async Task<IActionResult> Update(int id)
        {
            try
            {
                var category = await _unitOfWork.Categories.GetByIdAsync(id) ?? throw new MovieCategoryNotFoundException();
                var categoryUpdateViewModel = new MovieCategoryUpdateViewModel
                {
                    Id = category.Id,
                    Name = category.Name
                };
                return View(categoryUpdateViewModel);
            }
            catch (Exception ex)
            {
                _notify.AddErrorToastMessage(ex.Message);
                _logger.LogError(ex.Message);
            }
            return RedirectToAction(nameof(Index));
        }

        [HttpPost]
        public async Task<IActionResult> Update(MovieCategoryUpdateViewModel model)
        {
            try
            {
                if(ModelState.IsValid)
                {
                    var updateDto = new MovieCategoryUpdateDto(model.Id, model.Name);
                    await _movieCategoryService.Update(updateDto);
                    _notify.AddSuccessToastMessage("Category Updated Successfully");
                    return RedirectToAction(nameof(Index));
                }
            }
            catch (Exception ex)
            {
                _notify.AddErrorToastMessage(ex.Message);
                _logger.LogError(ex.Message);
            }
            return View(model);
        }
    }
}

ETicketing/Views/MovieCategory/Create.cshtml
@model ETicketing.ViewModels.MovieCategory.MovieCategoryCreateViewModel

@{
    ViewData["Title"] = "Add new category";
}

<div class="row text">
    <div class="card col-md-8 offset-2">
        <div class="col-md-12">
            <div class="card-header">
                <h4>@ViewData["Title"] </h4>
            </div>
            <div class="row">
                <div class="col-md-12 ">
                    <form asp-action="Create" enctype="multipart/form-data">
                        <div asp-validation-summary="ModelOnly" class="text-danger"></div>


                        <div class="form-group  mt-2">
                            <label class="control-label">  Name</label>
                            <input asp-for="Name" class="form-control" />
                            <span asp-validation-for="Name" class="text-danger"></span>
                        </div>


                        <div class="card-footer text-muted  mt-2">
                            <button type="submit" class="btn btn-outline-success float-right"><i class="bi bi-check-circle-fill"></i> Create</button>
                            <a class="btn btn-outline-secondary" asp-action="Index"><i class="bi bi-arrow-left-circle-fill"></i> Back</a>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

ETicketing/Views/MovieCategory/Index.cshtml
@model IEnumerable<ETicketing.ViewModels.MovieCategory.MovieCategoryIndexViewModel>

@{
    ViewData["Title"] = "List of Category";

}

<div class="row">
    <div class="card">
        <h5 class="card-header bg-primary text-white">@ViewData["Title"]</h5>
        <div class="card-body">
            <div class=col-md-12>
                <a class="btn-secondary btn btn-sm " asp-controller="MovieCategory" asp-action="Create">  <i class="bi bi-plus-circle"></i> Add</a>
            </div>
            <div class="col-md-12 mt-2 ">

                <table class=table table-bordered>
                    <thead>
                        <tr class="card-header">
                            <th>Id</th>
                            <th> Name</th>                          
                            <th>Actions</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model)
                        {
                            <tr>
                                <td >
                                    @Html.DisplayFor(modelItem => item.Id)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.Name)
                                </td>
                               
                                <td >
                                    <a class="btn btn-outline-primary btn-sm" asp-action="Update" asp-route-id="@item.Id"><i class="bi bi-pencil-square"></i> Edit </a>
                                </td>


                            </tr>
                        }
                    </tbody>

                </table>

            </div>
        </div>
    </div>
</div>

ETicketing/Views/MovieCategory/Update.cshtml
@model ETicketing.ViewModels.MovieCategory.MovieCategoryUpdateViewModel

@{
    ViewData["Title"] = "Update  category";
}

<div class="row text">
    <div class=" card col-md-8 offset-2">
       <div class="col-md-12">
            <div class="card-header">
                <h4>@ViewData["Title"] </h4>
            </div>
        <div class="row">
            <div class="col-md-12">
                <form asp-action="Update" enctype="multipart/form-data">
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                    <input asp-for="Id" hidden />
                   
                    <div class="form-group  mt-2">
                        <label  class="control-label">  Name</label>
                        <input asp-for="Name" class="form-control" />
                        <span asp-validation-for="Name" class="text-danger"></span>
                    </div>
                   

                    <div class="card-footer text-muted  mt-2">
                         <button type="submit"  class="btn btn-outline-success float-right"><i class="bi bi-check-circle-fill"></i> Update</button>
                        <a class="btn btn-outline-secondary" asp-action="Index"><i class="bi bi-arrow-left-circle-fill"></i> Back</a>
                 
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
</div>